###########################
#      Reading State      #
###########################
- platform: template
  sensors:
    reading_state:
      friendly_name: Lesen Szene
      value_template: off

###########################
#      Bedtime State      #
###########################
- platform: template
  sensors:
    bed_time_state:
      friendly_name: Bettzeit Szene
      value_template: off

###########################
#       Sleep State       #
###########################
- platform: template
  sensors:
    sleep_state:
      friendly_name: Schlafen Szene
      value_template: off
