- id: '1534167808220'
  alias: 99_deley_test
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:00:30
  - data:
      message: Heimsteuerung hochgefahren.
    service: tts.google_say
- id: '1534438742026'
  alias: 99_Script_Call_Test
  trigger:
  - entity_id: device_tracker.dominiciphone
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.1534438626592
- id: '1606162668106'
  alias: Inactivate living room switch by inactivity
  description: Inactivate switch in the living room, when inactive.
  trigger:
  - platform: time_pattern
    minutes: /28
  condition: []
  action:
  - service: script.turn_off_living_room_switch_if_inactive
    data: {}
    entity_id: switch.neq1662966
  mode: single
- id: '1606163058397'
  alias: Inactivate office switch by inactivity
  description: Inactivates the office switch, when inactive.
  trigger:
  - platform: time_pattern
    minutes: /29
  condition: []
  action:
  - service: script.turn_off_office_switch_if_inactive
    data: {}
    entity_id: switch.neq1662964
  mode: single
- id: '1606163996577'
  alias: Inactivate kitchen switch by inactivity
  description: Inactivate kitchen switch, when inactive.
  trigger:
  - platform: time_pattern
    minutes: /27
  condition: []
  action:
  - service: script.turn_off_kitchen_switch_if_inactive
    data: {}
    entity_id: switch.neq1662965
  mode: single
