- id: '1534167808220'
  alias: 99_deley_test
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:00:30
  - data:
      message: Heimsteuerung hochgefahren.
    service: tts.google_say
- id: '1534438742026'
  alias: 99_Script_Call_Test
  trigger:
  - entity_id: device_tracker.dominiciphone
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.1534438626592
