###########################
#    Sleep Mode Switch    #
###########################
# The Switch turns on/off the Bed Mode Automation.
# Bed Mode ON performs the following steps:
# 1. Turn on bed light.
# 2. Turn on table light at the bed with bedtime light.
# 3. Turn on radio with chilling music.
# Sleep Mode OFF performs the following steps:
# 1. Turn on sleep mode.
- platform: template
  switches:
    bed_time_mode:
      friendly_name: "Bettzeit"
      value_template: "{{ is_state('device_tracker.dominicstate', 'bedtime') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
          entity_id: scene.Bedtime
        service: device_tracker.see
        data:
          dev_id: dominicstate
          location_name: 'bedtime'
      turn_off:
        service: homeassistant.turn_on
        data:
          entity_id: scene.Sleep
      icon_template: >-
        {% if is_state('scene.Bedtime', 'on') %}
          mdi:bed-empty
        {% else %}
          mdi:hotel
        {% endif %}
