- platform: template
  switches:
    bed_time_mode:
      friendly_name: "Bettzeit"
#        value_template: "{{ is_state('device_tracker.dominiciphone', 'sleep') }}"
      value_template: "false"
      turn_on:
        service: homeassistant.turn_on
        data:
          entity_id: scene.Bedtime
      turn_off:
        service: homeassistant.turn_off
        data:
          entity_id: scene.Bedtime
      icon_template: >-
        {% if is_state('scene.Bedtime', 'on') %}
          mdi:bed-empty
        {% else %}
          mdi:hotel
        {% endif %}
