###########################
#    Read Mode Switch     #
###########################
# The Switch turns on/off the Bed Mode Automation.
# Bed Mode ON performs the following steps:
# 1. Turn on bed light.
# 2. Turn on table light at the bed with reading light.
# Read Mode OFF performs the following steps:
# 1. Turn on Bedtime mode.
- platform: template
  switches:
    read_mode:
      friendly_name: "Lesen"
      value_template: "{{ is_state('device_tracker.dominicstate', 'read') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
          entity_id: scene.Read
        service: device_tracker.see
        data:
          dev_id: dominicstate
          location_name: 'read'
      turn_off:
        service: homeassistant.turn_on
        data:
          entity_id: switch.bed_time_mode
      icon_template: >-
        {% if is_state('scene.Read', 'on') %}
          mdi:book-open-page-variant
        {% else %}
          mdi:book-outline
        {% endif %}
