###########################
#    Sleep Mode Switch    #
###########################
# The Switch turns on/off the Sleep Mode Automation.
# Sleep Mode ON performs the following steps:
# 1. Turn on bed light if sun is not up yet.
# 2. Turn on radio in the bed room and turn up the volume a little after every few minutes.
# 3. Turn on the TV for breakfast program.
# Sleep Mode OFF performs the following steps:
# 1. Turn off all phyiscal Homegear switches if on.
# 2. Turn off radio in bed room if on.
# 3. Turn off lights in the bedroom in a 30 seconds transition.
- platform: template
  switches:
    flat_sleep_mode:
      friendly_name: "Schlafmodus"
      value_template: "{{ is_state('device_tracker.dominicstate', 'sleep') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
          entity_id: scene.Sleep
#        service: device_tracker.see
#        data:
#          dev_id: dominicstate
#          location_name: 'sleep'
      turn_off:
        service: homeassistant.turn_on
        data:
          entity_id: scene.Awake
#        service: device_tracker.see
#        data:
#          dev_id: dominicstate
#          location_name: 'awake'
      icon_template: >-
        {% if is_state('scene.Sleep', 'on') %}
          mdi:sleep
        {% else %}
          mdi:sleep-off
        {% endif %}
