- platform: template
  switches:
    flat_sleep_mode:
      friendly_name: "Schlafmodus"
#        value_template: "{{ is_state('device_tracker.dominiciphone', 'sleep') }}"
      value_template: "false"
      turn_on:
        service: homeassistant.turn_off
        data:
          entity_id: scene.Awake
        service: homeassistant.turn_on
        data:
          entity_id: scene.Sleep
      turn_off:
        service: homeassistant.turn_off
        data:
          entity_id: scene.Sleep
        service: homeassistant.turn_on
        data:
          entity_id: scene.Awake
      icon_template: >-
        {% if is_state('scene.Sleep', 'on') %}
          mdi:sleep
        {% else %}
          mdi:sleep-off
        {% endif %}
