# OpenWeather Sensors
- platform: template
  sensors:
    openweather_temp:
      value_template: '{{ states.weather.ruit_forecast.attributes.temperature }}'
      unit_of_measurement: '°C'
      friendly_name: Temperatur Draußen
- platform: template
  sensors:
    openweather_wind:
      value_template: '{{ states.weather.ruit_forecast.attributes.wind_speed }}'
      unit_of_measurement: 'km/s'
      friendly_name: Wind
