###########################
#      Reading State      #
###########################
- platform: template
  sensors:
    reading_state:
      value_template: off
      friendly_name: Lesen Szene

###########################
#      Bedtime State      #
###########################
- platform: template
  sensors:
    bed_time_state:
      value_template: off
      friendly_name: Bettzeit Szene

###########################
#       Sleep State       #
###########################
- platform: template
  sensors:
    sleep_state:
      value_template: off
      friendly_name: Schlafen Szene
